name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每天 UTC 02:00 运行一次
    - cron: '0 2 * * *'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --buildDrafts=false --buildFuture=false

      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --verbose --no-progress './public/**/*.html'
          fail: true